export default class Telnet {
    socket: any;
    state: string;
    connect(opts: any): any;
    timeout: any;
    shellPrompt: any;
    loginPrompt: any;
    passwordPrompt: any;
    failedLoginMatch: any;
    loginPromptReceived: boolean;
    extSock: any;
    debug: any;
    username: any;
    password: any;
    irs: any;
    ors: any;
    echoLines: any;
    stripShellPrompt: any;
    pageSeparator: any;
    negotiationMandatory: any;
    initialLFCR: any;
    initialCTRLC: any;
    execTimeout: any;
    sendTimeout: any;
    maxBufferLength: any;
    inputBuffer: string;
    shell(callback: any): any;
    exec(cmd: any, opts: any, callback: any): any;
    send(data: any, opts: any, callback: any): any;
    waitfor: any;
    getSocket(): any;
    end(): any;
    destroy(): any;
    _parseData(chunk: any, callback: any): any;
    response: string[];
    _login(handle: any): void;
    _negotiate(chunk: any): any;
    _checkSocket(sock: any): boolean;
}
